# file: roles/cdh5_ot/tasks/install.yml

- name: install_cdh5_ot
  yum: name={{ item }} state=installed
  with_items:
    - hadoop-mapreduce-historyserver
    - hadoop-yarn-proxyserver

  tags:
    - cdh5_ot

