#file: playbooks/cdh5_pseudo/conf/cdh5_pseudo.yml

- hosts: "{{ server | default('cdh5_pseudo') }}"
  roles:
    - common
    - users
    - screen
    - ntp
    - prompt
    - epel
    - jdk
    - cdh5_pseudo
