# file: roles/ansible/tasks/conf.yml

- name: check_ansible_hosts_exists
  shell: test -f /etc/ansible/hosts
  register: check_ansible_hosts_exists
  ignore_errors: yes
  always_run: yes
  tags:
    - ansible

- name: make_link_of_hosts_for_each_environment
  file: src=/etc/ansible/hosts.{{ ansible_environment }} path=/etc/ansible/hosts state=link
  when: check_ansible_hosts_exists | failed
  tags:
    - ansible
