# file: single_shot/hadoop_cdh5_pseudo/create_user_dir.yml

- hosts: hadoop_cdh5_pseudo
  gather_facts: no
  sudo: True
  sudo_user: hdfs
  tasks:
    - name: make_user_dir
      shell: hdfs dfs -mkdir -p /user/{{ yarn_user | default('vagrant') }}

    - name: chown_user_dir
      shell: hdfs dfs -chown -R {{ yarn_user | default('vagrant') }} /user/{{ yarn_user | default('vagrant') }}

