# file: roles/java/tasks/conf.yml

- name: copy_bash_profile
  copy: src=java.sh dest=/etc/profile.d/
  when: jdk_use_oraclejdk

- name: copy_sudoers_conf_of_JAVA_HOME
  copy: src=env_keep_javahome dest=/etc/sudoers.d mode=440 owner=root
