# file: roles/jdk/tasks/main.yml

# repo
- include: repo.yml tags=jdk,repo
  when: jdk_direct == False

# install
- include: install_openjdk.yml tags=jdk,install
  when: jdk_use_openjdk == True
- include: install_oraclejdk.yml tags=jdk,install
  when: jdk_direct == False and jdk_use_oraclejdk == True
- include: install_direct.yml tags=jdk,install
  when: jdk_direct == True and jdk_use_oraclejdk == True

# conf
- include: conf.yml tags=jdk,conf
