# file: roles/hadoop_cdh5_slave/tasks/install.yml

- name: install_hadoop_cdh5_slave
  yum: name={{ item }} state=installed
  with_items:
    - hadoop-yarn-nodemanager
    - hadoop-hdfs-datanode
    - hadoop-mapreduce

  tags:
    - hadoop_cdh5_slave

